# Вариант №13

### Крайников Иван Александрович, РТ5-61б

In [16]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score

In [17]:
# загрузка данных и разделение на обучающую и тестовую выборки
%matplotlib inline 
sns.set(style="ticks")
data = pd.read_csv('marvel-wikia-data.csv', sep=",", encoding='latin1')
data = data.dropna(axis=0, how='any')
data.drop(['name', 'urlslug', 'GSM', 'FIRST APPEARANCE'], axis=1, inplace=True)

data.head(10)

,page_id,ID,ALIGN,EYE,HAIR,SEX,ALIVE,APPEARANCES,Year
28,6545,Public Identity,Good Characters,Green Eyes,Red Hair,Female Characters,Living Characters,1050.0,1964.0
42,1818,No Dual Identity,Good Characters,Blue Eyes,Brown Hair,Male Characters,Living Characters,725.0,1965.0
45,2307,Secret Identity,Neutral Characters,Blue Eyes,Purple Hair,Female Characters,Living Characters,708.0,1976.0
61,2042,No Dual Identity,Neutral Characters,Green Eyes,Black Hair,Genderfluid Characters,Living Characters,532.0,1949.0
71,1409,Secret Identity,Neutral Characters,Brown Eyes,Bald,Male Characters,Living Characters,500.0,1991.0
101,55878,Secret Identity,Bad Characters,Yellow Eyes,Red Hair,Female Characters,Living Characters,371.0,1978.0
117,2182,Secret Identity,Good Characters,Blue Eyes,Bald,Female Characters,Living Characters,323.0,1973.0
125,2238,Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,Living Characters,313.0,1979.0
175,2335,Secret Identity,Good Characters,Blue Eyes,Red Hair,Male Characters,Living Characters,237.0,1960.0
181,2353,Secret Identity,Good Characters,Brown Eyes,Brown Hair,Male Characters,Living Characters,231.0,1987.0

In [18]:
data['ID'].unique()

ID_type_dict = {
    'Public Identity': 0,
    'Secret Identity': 1,
    'No Dual Identity': 2,
}

data['ID'] = data['ID'].map(ID_type_dict)

In [19]:
data['ALIGN'].unique()

ALIGN_type_dict = {
    'Good Characters': 0,
    'Bad Characters': 1,
    'Neutral Characters': 2,
}

data['ALIGN'] = data['ALIGN'].map(ALIGN_type_dict)

In [20]:
data['EYE'].unique()

EYE_type_dict = {
    'Blue Eyes': 0,
    'Brown Eyes': 1,
    'Green Eyes': 2,
    'Yellow Eyes': 3,
    'Red Eyes': 4,
    'Black Eyes': 5,
    'White Eyes': 6,
    'Grey Eyes': 7,
    'Hazel Eyes': 8,
    'Variable Eyes': 9,
}

data['EYE'] = data['EYE'].map(EYE_type_dict)

In [21]:
data['HAIR'].unique()

HAIR_type_dict = {
    'Red Hair': 0,
    'Brown Hair': 1,
    'Purple Hair': 2,
    'Black Hair': 3,
    'Bald': 4,
    'Strawberry Blond Hair': 5,
    'Blond Hair': 6,
    'Silver Hair': 7,
    'White Hair': 8,
    'No Hair': 9,
    'Reddish Blond Hair': 10,
    'Variable Hair': 11,
}

data['HAIR'] = data['HAIR'].map(HAIR_type_dict)

In [22]:
data['SEX'].unique()

SEX_type_dict = {
    'Male Characters': 0,
    'Female Characters': 1,
    'Genderfluid Characters': 2,
}

data['SEX'] = data['SEX'].map(SEX_type_dict)

In [23]:
data['ALIVE'].unique()

ALIVE_type_dict = {
    'Living Characters': 0,
    'Deceased Characters': 1,
}

data['ALIVE'] = data['ALIVE'].map(ALIVE_type_dict)
data

       page_id  ID  ALIGN  EYE  HAIR  SEX  ALIVE  APPEARANCES    Year
28        6545   0      0    2     0    1      0       1050.0  1964.0
42        1818   2      0    0     1    0      0        725.0  1965.0
45        2307   1      2    0     2    1      0        708.0  1976.0
61        2042   2      2    2     3    2      0        532.0  1949.0
71        1409   1      2    1     4    0      0        500.0  1991.0
101      55878   1      1    3     0    1      0        371.0  1978.0
117       2182   1      0    0     4    1      0        323.0  1973.0
125       2238   1      0    0     3    0      0        313.0  1979.0
175       2335   1      0    0     0    0      0        237.0  1960.0
181       2353   1      0    1     1    0      0        231.0  1987.0
217      51769   1      1    0     3    0      0        189.0  2006.0
221      15901   1      0    1     3    0      0        184.0  2003.0
275       2023   1      0    0     5    1      0        150.0  1984.0
318      18271   0      0    0     0    1      0        131.0  1988.0
355       6637   1      0    1     3    0      0        119.0  2005.0
368       1465   2      0    9     3    0      0        113.0  2001.0
369       2298   1      0    1     3    0      0        113.0  2003.0
376       2029   1      0    1     3    0      0        111.0  1990.0
404       6636   0      0    0     6    0      0        103.0  2005.0
426     195422   2      2    8     3    1      1         98.0  2009.0
474      14482   1      0    0     6    1      0         86.0  2003.0
488       1424   1      2    6     7    1      1         82.0  1981.0
565       1561   2      2    1     3    1      0         68.0  1982.0
591       1887   1      0    0     6    1      1         65.0  1972.0
625     318208   0      0    1     3    0      0         62.0  2010.0
666     441087   0      0    0     0    0      0         57.0  2011.0
677      19283   0      0    0     8    1      1         56.0  2004.0
758       2628   1      1    0     3    1      0         49.0  1991.0
788     165982   2      0    6     9    0      0         48.0  2008.0
816       2415   1      0    1     1    0      1         46.0  2001.0
828       2603   0      2    2     3    1      0         45.0  2001.0
935       1759   1      1    1     1    1      0         40.0  1979.0
952     571723   2      0    1     1    0      0         40.0  2013.0
1106     17016   1      0    1     1    0      0         34.0  1989.0
1108    111303   1      2    5     3    1      0         34.0  1992.0
1154     23853   1      0    1     1    2      0         33.0  2005.0
1446     22800   1      1    0     6    0      1         26.0  2006.0
1620    514282   1      0    8     3    0      0         23.0  2010.0
1622    571073   2      2    2     6    0      0         23.0  2013.0
1762    339676   0      0    1     3    0      0         21.0  2009.0
2027    351736   1      2    5     3    1      0         18.0  2010.0
2145    532006   2      0    7     1    0      0         17.0  2012.0
2353    167996   1      0    4     9    1      0         15.0  1995.0
2394    532008   2      0    8    10    0      0         15.0  2012.0
2434    111227   2      2    8     1    0      1         14.0  1975.0
2890     93360   1      0    2     1    1      1         12.0  2008.0
2903    516101   2      0    1     1    0      0         12.0  2012.0
2905    591732   0      0    0     1    1      0         12.0  2013.0
3092    578698   1      0    0     3    1      0         11.0  2013.0
3309     29673   0      0    5     6    0      1         10.0  2006.0
3809     18536   1      0    1     3    0      0          8.0  1991.0
3925    111901   0      0    1     1    1      0          8.0  2004.0
4345    121255   1      2    0     6    0      0          7.0  2003.0
4424    490836   1      1    2     3    0      0          7.0  2011.0
6626    278334   0      1    1     1    1      0          4.0  2003.0
6870    438186   1      1    1     3    1      0          4.0  2011.0
7945      1217   0      0    6    11    0      1          3.0  2001.0
14106   106522   0      0    1     1    1      0          1.0  2002.0

In [24]:
X = data.drop('SEX', axis=1)
y = data['SEX']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [25]:
# Стандартизация данных
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
# ДЕРЕВО РЕШЕНИЙ
from sklearn.tree import DecisionTreeClassifier

# Создание и обучение модели дерева решений
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

# Предсказание и оценка
y_pred_tree = tree_model.predict(X_test)
accuracy_tree = accuracy_score(y_test, y_pred_tree)
f1_tree = f1_score(y_test, y_pred_tree , average='weighted')

print(f'Decision Tree - Accuracy: {accuracy_tree}, F1-Score: {f1_tree}')

Decision Tree - Accuracy: 0.4444444444444444, F1-Score: 0.4328249818445897

In [27]:
# ГРАДИЕНТНЫЙ БУСТИНГ
from sklearn.ensemble import GradientBoostingClassifier

# Создание и обучение модели градиентного бустинга
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

# Предсказание и оценка
y_pred_gb = gb_model.predict(X_test)
accuracy_gb = accuracy_score(y_test, y_pred_gb)
f1_gb = f1_score(y_test, y_pred_gb, average='weighted')

print(f'Gradient Boosting - Accuracy: {accuracy_gb}, F1-Score: {f1_gb}')

Gradient Boosting - Accuracy: 0.3333333333333333, F1-Score: 0.3216374269005848

In [28]:
# РЕЗУЛЬТАТЫ
print(f'Decision Tree - Accuracy: {accuracy_tree}, F1-Score: {f1_tree}')
print(f'Gradient Boosting - Accuracy: {accuracy_gb}, F1-Score: {f1_gb}')

Decision Tree - Accuracy: 0.4444444444444444, F1-Score: 0.4328249818445897
Gradient Boosting - Accuracy: 0.3333333333333333, F1-Score: 0.3216374269005848

### <b>Выводы</b>
- Модель градиентного бустинга показала более низкие значения Accuracy и F1-Score по сравнению с моделью дерева решений, что указывает на худшую общую производительность.
- Модель дерева решений, хотя и является простой в интерпретации и реализации, но не уступает в качестве предсказаний более сложным моделям, таким как градиентный бустинг, особенно на комплексных данных.